version: '3.8'
services:

  redis-7000:
    image: redis:latest
    restart: always
    ports:
      - "7000:7000"
    volumes:
      - ./7000/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      app_net:
        ipv4_address: 173.17.0.2

  redis-7001:
    image: redis:latest
    restart: always
    ports:
      - "7001:7001"
    volumes:
      - ./7001/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      app_net:
        ipv4_address: 173.17.0.3

  redis-7002:
    image: redis:latest
    restart: always
    ports:
      - "7002:7002"
    volumes:
      - ./7002/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      app_net:
        ipv4_address: 173.17.0.4

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16
